package jp.cte2.forgeuiinspector.client;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.ItemStack;

/** Production-sized currency stash preview; intentionally independent of MapStashPreviewScreen. */
public final class CurrencyStashPreviewScreen extends Screen {
    private static final int W = Cte2StashPreviewGeometry.WIDTH, H = Cte2StashPreviewGeometry.HEIGHT; private final Screen parent;
    private CurrencyPreviewFixture fixture = CurrencyPreviewFixture.NORMAL; private int fixtureIndex, category, page, scroll; private float scale = 1; private int ox, oy;
    public CurrencyStashPreviewScreen(Screen parent) { super(Component.translatable("screen.forgeuiinspector.currency.title")); this.parent = parent; }
    @Override protected void init() { scale = Math.min(1, Math.min(width / (float) W, height / (float) H)); ox = Math.round((width - W * scale) / 2); oy = Math.round((height - H * scale) / 2); }
    @Override public void render(GuiGraphics g, int mx, int my, float partial) { renderBackground(g); g.pose().pushPose(); g.pose().translate(ox, oy, 0); g.pose().scale(scale, scale, 1); g.fill(0, 0, W, H, 0xff202124); g.fill(1, 1, W - 1, 20, 0xff383b40); g.drawString(font, title, 8, 6, 0xffffff, false); g.fill(216, 3, 313, 18, 0xff4b5260); Component fixtureText = Component.translatable("screen.forgeuiinspector.fixture", Component.translatable(fixture.translationKey())); g.drawString(font, font.substrByWidth(fixtureText, 90).getString(), 220, 6, 0xffffff, false); g.fill(Cte2StashPreviewGeometry.LIST_X, Cte2StashPreviewGeometry.LIST_Y, Cte2StashPreviewGeometry.LIST_X + Cte2StashPreviewGeometry.LIST_WIDTH, Cte2StashPreviewGeometry.LIST_Y + Cte2StashPreviewGeometry.LIST_ROWS * Cte2StashPreviewGeometry.LIST_ROW_HEIGHT, 0xff151619); drawCategories(g); drawSlots(g); drawInventory(g); g.pose().popPose(); super.render(g, mx, my, partial); }
    private void drawCategories(GuiGraphics g) { var names = fixture.categories(); scroll = LayoutMath.clampScroll(scroll, names.size(), Cte2StashPreviewGeometry.LIST_ROWS); for (int row = 0; row < Cte2StashPreviewGeometry.LIST_ROWS && row + scroll < names.size(); row++) { int i = row + scroll, y = Cte2StashPreviewGeometry.LIST_Y + row * Cte2StashPreviewGeometry.LIST_ROW_HEIGHT; if (i == category) g.fill(Cte2StashPreviewGeometry.LIST_X + 2, y, Cte2StashPreviewGeometry.LIST_X + Cte2StashPreviewGeometry.LIST_WIDTH - 2, y + Cte2StashPreviewGeometry.LIST_ROW_HEIGHT, 0xff4b5260); g.drawString(font, font.substrByWidth(names.get(i), 160).getString(), Cte2StashPreviewGeometry.LIST_X + 7, y + 5, 0xe8e8e8, false); } }
    private void drawSlots(GuiGraphics g) { int x = Cte2StashPreviewGeometry.STASH_X, y = Cte2StashPreviewGeometry.STASH_Y, count = fixture.categoryCount(category), pages = fixture.pageCountForCategory(category), shown = Math.min(Cte2StashPreviewGeometry.PAGE_SIZE, Math.max(0, count - page * Cte2StashPreviewGeometry.PAGE_SIZE)); for (int i = 0; i < Cte2StashPreviewGeometry.PAGE_SIZE; i++) { int sx = x + (i % Cte2StashPreviewGeometry.STASH_COLUMNS) * Cte2StashPreviewGeometry.SLOT_SIZE, sy = y + (i / Cte2StashPreviewGeometry.STASH_COLUMNS) * Cte2StashPreviewGeometry.SLOT_SIZE; drawSlot(g, sx, sy, i < shown ? fixture.itemForCategory(category, page * Cte2StashPreviewGeometry.PAGE_SIZE + i) : ItemStack.EMPTY); } if (pages > 1) { g.drawString(font, Component.translatable("screen.forgeuiinspector.page", page + 1, pages), Cte2StashPreviewGeometry.PAGE_LABEL_X, Cte2StashPreviewGeometry.PAGE_LABEL_Y, 0xffffff, false); g.fill(Cte2StashPreviewGeometry.PAGE_PREVIOUS_X, Cte2StashPreviewGeometry.PAGE_BUTTON_Y, Cte2StashPreviewGeometry.PAGE_PREVIOUS_X + Cte2StashPreviewGeometry.PAGE_BUTTON_WIDTH, Cte2StashPreviewGeometry.PAGE_BUTTON_Y + Cte2StashPreviewGeometry.PAGE_BUTTON_HEIGHT, 0xff4b5260); g.fill(Cte2StashPreviewGeometry.PAGE_NEXT_X, Cte2StashPreviewGeometry.PAGE_BUTTON_Y, Cte2StashPreviewGeometry.PAGE_NEXT_X + Cte2StashPreviewGeometry.PAGE_BUTTON_WIDTH, Cte2StashPreviewGeometry.PAGE_BUTTON_Y + Cte2StashPreviewGeometry.PAGE_BUTTON_HEIGHT, 0xff4b5260); } }
    private void drawInventory(GuiGraphics g) { int x = Cte2StashPreviewGeometry.INVENTORY_X; g.drawString(font, Component.translatable("container.inventory"), Cte2StashPreviewGeometry.INVENTORY_LABEL_X, Cte2StashPreviewGeometry.INVENTORY_LABEL_Y, 0xffbdbdbd, false); for (int i = 0; i < Cte2StashPreviewGeometry.INVENTORY_COLUMNS * Cte2StashPreviewGeometry.INVENTORY_ROWS; i++) drawSlot(g, x + (i % Cte2StashPreviewGeometry.INVENTORY_COLUMNS) * Cte2StashPreviewGeometry.SLOT_SIZE, Cte2StashPreviewGeometry.INVENTORY_Y + (i / Cte2StashPreviewGeometry.INVENTORY_COLUMNS) * Cte2StashPreviewGeometry.SLOT_SIZE, ItemStack.EMPTY); for (int i = 0; i < Cte2StashPreviewGeometry.HOTBAR_COLUMNS; i++) drawSlot(g, x + i * Cte2StashPreviewGeometry.SLOT_SIZE, Cte2StashPreviewGeometry.HOTBAR_Y, ItemStack.EMPTY); }
    private void drawSlot(GuiGraphics g, int x, int y, ItemStack stack) { g.fill(x, y, x + Cte2StashPreviewGeometry.SLOT_SIZE, y + Cte2StashPreviewGeometry.SLOT_SIZE, 0xff8b8b8b); g.fill(x + 1, y + 1, x + Cte2StashPreviewGeometry.SLOT_SIZE - 1, y + Cte2StashPreviewGeometry.SLOT_SIZE - 1, 0xff373737); g.fill(x + 1, y + 1, x + Cte2StashPreviewGeometry.SLOT_SIZE - 1, y + 2, 0xffb6b6b6); g.fill(x + 1, y + 1, x + 2, y + Cte2StashPreviewGeometry.SLOT_SIZE - 1, 0xffb6b6b6); g.fill(x + 1, y + Cte2StashPreviewGeometry.SLOT_SIZE - 2, x + Cte2StashPreviewGeometry.SLOT_SIZE - 1, y + Cte2StashPreviewGeometry.SLOT_SIZE - 1, 0xff202020); g.fill(x + Cte2StashPreviewGeometry.SLOT_SIZE - 2, y + 1, x + Cte2StashPreviewGeometry.SLOT_SIZE - 1, y + Cte2StashPreviewGeometry.SLOT_SIZE - 1, 0xff202020); if (!stack.isEmpty()) { g.renderItem(stack, x + 1, y + 1); g.renderItemDecorations(font, stack, x + 1, y + 1); } }
    private double lx(double x) { return (x - ox) / scale; } private double ly(double y) { return (y - oy) / scale; }
    private void next(int step) { fixtureIndex = (fixtureIndex + step + 4) % 4; fixture = CurrencyPreviewFixture.values()[fixtureIndex]; category = page = scroll = 0; }
    @Override public boolean mouseScrolled(double mx, double my, double amount) { if (lx(mx) >= Cte2StashPreviewGeometry.LIST_X && lx(mx) < Cte2StashPreviewGeometry.LIST_X + Cte2StashPreviewGeometry.LIST_WIDTH) scroll += amount > 0 ? -1 : 1; else page += amount > 0 ? -1 : 1; scroll = LayoutMath.clampScroll(scroll, fixture.categories().size(), Cte2StashPreviewGeometry.LIST_ROWS); page = Math.max(0, Math.min(fixture.pageCountForCategory(category) - 1, page)); return true; }
    @Override public boolean mouseClicked(double mx, double my, int button) { double x = lx(mx), y = ly(my); if (x >= 216 && x < 314 && y >= 2 && y < 20) { next(1); return true; } if (x >= Cte2StashPreviewGeometry.PAGE_PREVIOUS_X && x < Cte2StashPreviewGeometry.PAGE_PREVIOUS_X + Cte2StashPreviewGeometry.PAGE_BUTTON_WIDTH && y >= Cte2StashPreviewGeometry.PAGE_BUTTON_Y && y < Cte2StashPreviewGeometry.PAGE_BUTTON_Y + Cte2StashPreviewGeometry.PAGE_BUTTON_HEIGHT) { page = Math.max(0, Math.min(fixture.pageCountForCategory(category) - 1, page - 1)); return true; } if (x >= Cte2StashPreviewGeometry.PAGE_NEXT_X && x < Cte2StashPreviewGeometry.PAGE_NEXT_X + Cte2StashPreviewGeometry.PAGE_BUTTON_WIDTH && y >= Cte2StashPreviewGeometry.PAGE_BUTTON_Y && y < Cte2StashPreviewGeometry.PAGE_BUTTON_Y + Cte2StashPreviewGeometry.PAGE_BUTTON_HEIGHT) { page = Math.max(0, Math.min(fixture.pageCountForCategory(category) - 1, page + 1)); return true; } if (x >= Cte2StashPreviewGeometry.LIST_X && x < Cte2StashPreviewGeometry.LIST_X + Cte2StashPreviewGeometry.LIST_WIDTH && y >= Cte2StashPreviewGeometry.LIST_Y && y < Cte2StashPreviewGeometry.LIST_Y + Cte2StashPreviewGeometry.LIST_ROWS * Cte2StashPreviewGeometry.LIST_ROW_HEIGHT) { category = Math.max(0, Math.min(fixture.categories().size() - 1, (int)((y - Cte2StashPreviewGeometry.LIST_Y) / Cte2StashPreviewGeometry.LIST_ROW_HEIGHT) + scroll)); page = 0; return true; } return super.mouseClicked(mx, my, button); }
    @Override public boolean keyPressed(int key, int scan, int modifiers) { if (key == 256) { onClose(); return true; } if (key == 262) { next(1); return true; } if (key == 263) { next(-1); return true; } return super.keyPressed(key, scan, modifiers); }
    @Override public void onClose() { Minecraft.getInstance().setScreen(parent); }
}
