package jp.cte2.forgeuiinspector.client;

import java.util.List;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.ItemStack;

/** Local-only preview on the production CTE2 stash logical canvas. */
public final class MapStashPreviewScreen extends Screen {
    private static final int W = Cte2StashPreviewGeometry.WIDTH, H = Cte2StashPreviewGeometry.HEIGHT;
    private final Screen parent;
    private PreviewFixture fixture = PreviewFixture.NORMAL;
    private int fixtureIndex, selectedLayout, scroll, page, originX, originY;
    private float scale = 1;
    public MapStashPreviewScreen(Screen parent) { super(Component.translatable("screen.forgeuiinspector.title")); this.parent = parent; this.fixtureIndex = PreviewLaunchOptions.fixtureIndex(); this.fixture = PreviewFixture.values()[fixtureIndex]; }
    @Override protected void init() { scale = Math.min(1, Math.min(width / (float) W, height / (float) H)); originX = Math.round((width - W * scale) / 2); originY = Math.round((height - H * scale) / 2); }
    @Override public void render(GuiGraphics g, int mouseX, int mouseY, float partialTick) {
        renderBackground(g); g.pose().pushPose(); g.pose().translate(originX, originY, 0); g.pose().scale(scale, scale, 1);
        g.fill(0, 0, W, H, 0xff202124); g.fill(1, 1, W - 1, 20, 0xff383b40); g.drawString(font, title, 8, 6, 0xffffff, false);
        g.fill(216, 3, 313, 18, 0xff4b5260); Component fixtureText = Component.translatable("screen.forgeuiinspector.fixture", Component.translatable(fixture.translationKey())); g.drawString(font, font.substrByWidth(fixtureText, 90).getString(), 220, 6, 0xffffff, false);
        drawLayoutList(g); drawStash(g); drawPlayerInventory(g); g.pose().popPose(); super.render(g, mouseX, mouseY, partialTick);
    }
    private void drawLayoutList(GuiGraphics g) {
        int x = Cte2StashPreviewGeometry.LIST_X, y = Cte2StashPreviewGeometry.LIST_Y; g.fill(x, y, x + Cte2StashPreviewGeometry.LIST_WIDTH, y + Cte2StashPreviewGeometry.LIST_ROWS * Cte2StashPreviewGeometry.LIST_ROW_HEIGHT, 0xff151619); List<Component> names = fixture.layoutLabels(); int visible = Cte2StashPreviewGeometry.LIST_ROWS; scroll = LayoutMath.clampScroll(scroll, names.size(), visible);
        for (int row = 0; row < visible && row + scroll < names.size(); row++) { int index = row + scroll, yy = y + row * Cte2StashPreviewGeometry.LIST_ROW_HEIGHT; if (index == selectedLayout) g.fill(x + 2, yy, x + Cte2StashPreviewGeometry.LIST_WIDTH - 2, yy + Cte2StashPreviewGeometry.LIST_ROW_HEIGHT, 0xff4b5260); String clipped = font.substrByWidth(names.get(index), 150).getString(); g.drawString(font, clipped, x + 7, yy + 5, 0xe8e8e8, false); g.drawString(font, Integer.toString(fixture.countForLayout(index)), x + Cte2StashPreviewGeometry.LIST_WIDTH - 20, yy + 5, 0xffb0b0b0, false); }
    }
    private void drawStash(GuiGraphics g) {
        int x = Cte2StashPreviewGeometry.STASH_X, y = Cte2StashPreviewGeometry.STASH_Y; String heading = font.substrByWidth(fixture.layoutLabel(selectedLayout), 110).getString() + " (" + fixture.countForLayout(selectedLayout) + ")"; g.drawString(font, heading, x, 20, 0xffd9d9d9, false);
        int selectedCount = selectedCount(); int shown = Math.min(Cte2StashPreviewGeometry.PAGE_SIZE, Math.max(0, selectedCount - page * Cte2StashPreviewGeometry.PAGE_SIZE));
        for (int i = 0; i < Cte2StashPreviewGeometry.PAGE_SIZE; i++) { int sx = x + (i % Cte2StashPreviewGeometry.STASH_COLUMNS) * Cte2StashPreviewGeometry.SLOT_SIZE, sy = y + (i / Cte2StashPreviewGeometry.STASH_COLUMNS) * Cte2StashPreviewGeometry.SLOT_SIZE; drawSlot(g, sx, sy, i < shown ? fixture.item(page * Cte2StashPreviewGeometry.PAGE_SIZE + i) : ItemStack.EMPTY); }
        int pages = fixture.pageCountFor(selectedCount); if (pages > 1) { g.drawString(font, Component.translatable("screen.forgeuiinspector.page", page + 1, pages), Cte2StashPreviewGeometry.PAGE_LABEL_X, Cte2StashPreviewGeometry.PAGE_LABEL_Y, 0xffffff, false); g.fill(Cte2StashPreviewGeometry.PAGE_PREVIOUS_X, Cte2StashPreviewGeometry.PAGE_BUTTON_Y, Cte2StashPreviewGeometry.PAGE_PREVIOUS_X + Cte2StashPreviewGeometry.PAGE_BUTTON_WIDTH, Cte2StashPreviewGeometry.PAGE_BUTTON_Y + Cte2StashPreviewGeometry.PAGE_BUTTON_HEIGHT, 0xff4b5260); g.fill(Cte2StashPreviewGeometry.PAGE_NEXT_X, Cte2StashPreviewGeometry.PAGE_BUTTON_Y, Cte2StashPreviewGeometry.PAGE_NEXT_X + Cte2StashPreviewGeometry.PAGE_BUTTON_WIDTH, Cte2StashPreviewGeometry.PAGE_BUTTON_Y + Cte2StashPreviewGeometry.PAGE_BUTTON_HEIGHT, 0xff4b5260); }
    }
    private void drawPlayerInventory(GuiGraphics g) { int x = Cte2StashPreviewGeometry.INVENTORY_X; g.drawString(font, Component.translatable("container.inventory"), Cte2StashPreviewGeometry.INVENTORY_LABEL_X, Cte2StashPreviewGeometry.INVENTORY_LABEL_Y, 0xffbdbdbd, false); for (int i = 0; i < Cte2StashPreviewGeometry.INVENTORY_COLUMNS * Cte2StashPreviewGeometry.INVENTORY_ROWS; i++) drawSlot(g, x + (i % Cte2StashPreviewGeometry.INVENTORY_COLUMNS) * Cte2StashPreviewGeometry.SLOT_SIZE, Cte2StashPreviewGeometry.INVENTORY_Y + (i / Cte2StashPreviewGeometry.INVENTORY_COLUMNS) * Cte2StashPreviewGeometry.SLOT_SIZE, ItemStack.EMPTY); for (int i = 0; i < Cte2StashPreviewGeometry.HOTBAR_COLUMNS; i++) drawSlot(g, x + i * Cte2StashPreviewGeometry.SLOT_SIZE, Cte2StashPreviewGeometry.HOTBAR_Y, new ItemStack(i % 2 == 0 ? net.minecraft.world.item.Items.BREAD : net.minecraft.world.item.Items.TORCH, 1)); }
    private void drawSlot(GuiGraphics g, int x, int y, ItemStack stack) { g.fill(x, y, x + Cte2StashPreviewGeometry.SLOT_SIZE, y + Cte2StashPreviewGeometry.SLOT_SIZE, 0xff8b8b8b); g.fill(x + 1, y + 1, x + Cte2StashPreviewGeometry.SLOT_SIZE - 1, y + Cte2StashPreviewGeometry.SLOT_SIZE - 1, 0xff373737); g.fill(x + 1, y + 1, x + Cte2StashPreviewGeometry.SLOT_SIZE - 1, y + 2, 0xffb6b6b6); g.fill(x + 1, y + 1, x + 2, y + Cte2StashPreviewGeometry.SLOT_SIZE - 1, 0xffb6b6b6); g.fill(x + 1, y + Cte2StashPreviewGeometry.SLOT_SIZE - 2, x + Cte2StashPreviewGeometry.SLOT_SIZE - 1, y + Cte2StashPreviewGeometry.SLOT_SIZE - 1, 0xff202020); g.fill(x + Cte2StashPreviewGeometry.SLOT_SIZE - 2, y + 1, x + Cte2StashPreviewGeometry.SLOT_SIZE - 1, y + Cte2StashPreviewGeometry.SLOT_SIZE - 1, 0xff202020); if (!stack.isEmpty()) { g.renderItem(stack, x + 1, y + 1); g.renderItemDecorations(font, stack, x + 1, y + 1); } }
    private double lx(double x) { return (x - originX) / scale; } private double ly(double y) { return (y - originY) / scale; }
    private int selectedCount() { return fixture.countForLayout(selectedLayout); }
    @Override public boolean mouseScrolled(double mx, double my, double amount) { if (lx(mx) >= Cte2StashPreviewGeometry.LIST_X && lx(mx) < Cte2StashPreviewGeometry.LIST_X + Cte2StashPreviewGeometry.LIST_WIDTH && ly(my) >= Cte2StashPreviewGeometry.LIST_Y && ly(my) < Cte2StashPreviewGeometry.LIST_Y + Cte2StashPreviewGeometry.LIST_ROWS * Cte2StashPreviewGeometry.LIST_ROW_HEIGHT) scroll += amount > 0 ? -1 : 1; else if (fixture.pageCountFor(selectedCount()) > 1) page += amount > 0 ? -1 : 1; scroll = LayoutMath.clampScroll(scroll, fixture.layoutLabels().size(), Cte2StashPreviewGeometry.LIST_ROWS); page = LayoutMath.pageFor(selectedCount(), Cte2StashPreviewGeometry.PAGE_SIZE, page); return true; }
    @Override public boolean mouseClicked(double mx, double my, int button) { double x = lx(mx), y = ly(my); if (x >= 216 && x < 314 && y >= 2 && y < 20) { nextFixture(); return true; } if (x >= Cte2StashPreviewGeometry.PAGE_PREVIOUS_X && x < Cte2StashPreviewGeometry.PAGE_PREVIOUS_X + Cte2StashPreviewGeometry.PAGE_BUTTON_WIDTH && y >= Cte2StashPreviewGeometry.PAGE_BUTTON_Y && y < Cte2StashPreviewGeometry.PAGE_BUTTON_Y + Cte2StashPreviewGeometry.PAGE_BUTTON_HEIGHT) { page = LayoutMath.pageFor(selectedCount(), Cte2StashPreviewGeometry.PAGE_SIZE, page - 1); return true; } if (x >= Cte2StashPreviewGeometry.PAGE_NEXT_X && x < Cte2StashPreviewGeometry.PAGE_NEXT_X + Cte2StashPreviewGeometry.PAGE_BUTTON_WIDTH && y >= Cte2StashPreviewGeometry.PAGE_BUTTON_Y && y < Cte2StashPreviewGeometry.PAGE_BUTTON_Y + Cte2StashPreviewGeometry.PAGE_BUTTON_HEIGHT) { page = LayoutMath.pageFor(selectedCount(), Cte2StashPreviewGeometry.PAGE_SIZE, page + 1); return true; } if (x >= Cte2StashPreviewGeometry.LIST_X && x < Cte2StashPreviewGeometry.LIST_X + Cte2StashPreviewGeometry.LIST_WIDTH && y >= Cte2StashPreviewGeometry.LIST_Y && y < Cte2StashPreviewGeometry.LIST_Y + Cte2StashPreviewGeometry.LIST_ROWS * Cte2StashPreviewGeometry.LIST_ROW_HEIGHT) { int row = (int)((y - Cte2StashPreviewGeometry.LIST_Y) / Cte2StashPreviewGeometry.LIST_ROW_HEIGHT) + scroll; if (row >= 0 && row < fixture.layoutLabels().size()) { selectedLayout = row; page = 0; } return true; } return super.mouseClicked(mx, my, button); }
    private void nextFixture() { fixtureIndex = (fixtureIndex + 1) % 4; fixture = PreviewFixture.values()[fixtureIndex]; selectedLayout = scroll = page = 0; }
    @Override public boolean keyPressed(int keyCode, int scanCode, int modifiers) { if (keyCode == 256) { onClose(); return true; } if (keyCode == 262) { nextFixture(); return true; } if (keyCode == 263) { fixtureIndex = (fixtureIndex + 3) % 4; fixture = PreviewFixture.values()[fixtureIndex]; selectedLayout = scroll = page = 0; return true; } return super.keyPressed(keyCode, scanCode, modifiers); }
    @Override public void onClose() { Minecraft.getInstance().setScreen(parent); }
}
